title: <p align="center">Jina Fan</p>
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/jinafan/">LinkedIn</a>
  </p>
  
  <p align="justify">
  Experienced financial professional with a detail-oriented and analytical approach, seeking new challenges. My curiosity and quick learning ability fuel my passion for observing, questioning, and solving complex financial problems. With a proven track record in financial analysis and reporting, I excel in leveraging tools like VBA, Excel, and Power BI for data manipulation, analysis, and visualization. My expertise lies in simplifying intricate financial scenarios and providing insightful, value-added solutions.
  </p>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


